apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver2
  labels:
    web: two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver2
  template:
    metadata:
      labels:
        app: webserver2
        dp: canary
    spec:
      containers:
      - name: webserver2
        image: httpd # <-- APACHE IMAGE
        # LIFECYCLE DEFINITION START 
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo WebServer2_$HOSTNAME > htdocs/index.html"]
        # LIFECYCLE DEFINITION END
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"